language: php
dist: bionic
php:
  - '7.2'
  - '7.3'
before_install:
  - sudo apt-get update
  - sudo apt install clamav-daemon
  - sudo service clamav-freshclam stop
  - sudo service clamav-daemon stop
  - sudo freshclam
  - sudo service clamav-daemon start
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v
