language: php
dist: bionic
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
before_install:
  - sudo apt-get update
  - sudo apt install clamav-daemon
  - sudo mkdir -p /run/clamav
  - sudo touch /run/clamav/clamd.sock
  - sudo chown clamav:clamav /run/clamav/clamd.sock
  - sudo service clamav-daemon restart
  - sudo freshclam
install:
  - composer update
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
