language: php
dist: bionic
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
before_install:
  - sudo apt-get update
  - sudo apt install clamav-daemon
  - sudo service clamav-freshclam stop
  - sudo service clamav-daemon stop
  - sudo mkdir -p /var/run/clamav
  - sudo touch /var/run/clamav/clamd.ctl
  - sudo chown clamav:clamav /var/run/clamav/clamd.ctl
  - sudo freshclam
  - sudo service clamav-daemon start
install:
  - composer update
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
