language: php
dist: bionic
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
before_install:
  - sudo apt-get update
  - sudo apt install clamav-daemon
  - sudo service clamav-freshclam stop
  - sudo service clamav-daemon stop

  # ClamAV's CDN has an aggressive rate limiter.  This is a workaround.
  - sudo sh -c "cat clamav-mirror/main.cvd/xaa clamav-mirror/main.cvd/xab clamav-mirror/main.cvd/xac clamav-mirror/main.cvd/xad clamav-mirror/main.cvd/xae clamav-mirror/main.cvd/xaf clamav-mirror/main.cvd/xag clamav-mirror/main.cvd/xah clamav-mirror/main.cvd/xai clamav-mirror/main.cvd/xaj clamav-mirror/main.cvd/xak clamav-mirror/main.cvd/xal > /var/lib/clamav/main.cvd"
  - sudo chown clamav:clamav /var/lib/clamav/main.cvd
  - sudo chmod 644 /var/lib/clamav/main.cvd
  - sudo cp clamav-mirror/bytecode.cvd /var/lib/clamav/
  - sudo chown clamav:clamav /var/lib/clamav/bytecode.cvd
  - sudo chmod 644 /var/lib/clamav/bytecode.cvd
  - sudo sh -c "cat clamav-mirror/daily.cvd/xaa clamav-mirror/daily.cvd/xab clamav-mirror/daily.cvd/xac clamav-mirror/daily.cvd/xad clamav-mirror/daily.cvd/xae clamav-mirror/daily.cvd/xaf clamav-mirror/daily.cvd/xag clamav-mirror/daily.cvd/xah clamav-mirror/daily.cvd/xai clamav-mirror/daily.cvd/xaj clamav-mirror/daily.cvd/xak clamav-mirror/daily.cvd/xal > /var/lib/clamav/daily.cvd"
  - sudo chown clamav:clamav /var/lib/clamav/daily.cvd
  - sudo chmod 644 /var/lib/clamav/daily.cvd

  # ClamAV sometimes has problems creating the this file for unknown reason.
  - sudo mkdir -p /run/clamav
  - sudo touch /run/clamav/clamd.ctl
  - sudo chown clamav:clamav /run/clamav/clamd.ctl

  - sudo service clamav-daemon start
install:
  - composer update
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
