language: php
dist: bionic
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
before_install:
  - sudo apt-get update
  - sudo apt install clamav-daemon
  - sudo service clamav-freshclam stop
  - sudo service clamav-daemon restart
  - sudo freshclam
  - sudo service clamav-daemon restart
install:
  - composer update
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
