language: php
dist: trusty
php:
  - '7.2'
  - '7.3'
install:
  - composer update
  - sudo apt install clamav-daemon
  - sudo freshclam
  - sudo service clamav-daemon restart
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v